apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: cert-manager
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: tls-cert
  commonName: test.demo.io
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - demo
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  usages:
    - server auth
    - client auth
  dnsNames:
    - test.demo.io
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default"