apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: demoperson@demo.no
    privateKeySecretRef:
      name: cert-issuer
    solvers:
      - http01:
          ingress:
            class: traefik