apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    [[tls.certificates]]
      certFile = "/tlscertificate/tls.crt"
      keyFile = "/tlscertificate/tls.key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: tlscertificate
        secret:
          secretName: tls-cert
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik:2.9.4
        name: traefik-ingress-lb
        env:
        - name: TRAEFIK_ENTRYPOINTS_PING
          value: "true"
        - name: TRAEFIK_ENTRYPOINTS_PING_ADDRESS
          value: :8082
        - name: TRAEFIK_ENTRYPOINTS_WEB
          value: "true"
        - name: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
          value: :80
        - name: TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO
          value: websecure
        - name: TRAEFIK_ENTRYPOINTS_WEBSECURE
          value: "true"
        - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS
          value: :443
        - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS
          value: "true"
        - name: TRAEFIK_LOG
          value: "true"
        - name: TRAEFIK_LOG_LEVEL
          value: INFO
        - name: TRAEFIK_PING
          value: "true"
        - name: TRAEFIK_PING_ENTRYPOINT
          value: ping
        - name: TRAEFIK_PROVIDERS_FILE_DIRECTORY
          value: "/config/"
        - name: TRAEFIK_PROVIDERS_KUBERNETESCRD
          value: "true"
        - name: TRAEFIK_PROVIDERS_KUBERNETESINGRESS
          value: "true"
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 80
          name: traefik-http
          protocol: TCP
        - containerPort: 443
          name: traefik-https
          protocol: TCP
        - containerPort: 8082
          name: traefik-ping
          protocol: TCP
        volumeMounts:
        - mountPath: "/tlscertificate"
          name: "tlscertificate"
        - mountPath: "/config"
          name: "config"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      tolerations:
      - key: frontend
        operator: Equal
        value: all
        effect: NoSchedule
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-ingress-controller-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: traefik-ingress-controller
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80