apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    defaultEntryPoints = ["https","http"]

    [retry]
    attempts = 3

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "tlscertificate/tls.crt"
          KeyFile = "tlscertificate/tls.key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: tlscertificate
        secret:
          secretName: tls-cert
      - name: config
        configMap:
          name: traefik-conf
      containers:
      - image: traefik:1.7.34
        name: traefik-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/tlscertificate"
          name: "tlscertificate"
        - mountPath: "/config"
          name: "config"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        args: 
        - --configfile=/config/traefik.toml
        - --kubernetes
        - --file
        - --file.directory=/config/
        - --file.watch=true
        - --logLevel=INFO
      tolerations:
      - key: frontend
        operator: Equal
        value: all
        effect: NoSchedule
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-ingress-controller-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: traefik-ingress-controller
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80